CREATE TABLE IF NOT EXISTS users
(
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    varchar(100),
    login     	varchar NOT NULL,
    email       varchar(50) NOT NULL,
    birthday    date NOT NULL
);

CREATE TABLE IF NOT EXISTS genres
(
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS mpa
(
    id 			integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name		varchar(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS films
(
    id 			integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name 		varchar(100) NOT NULL,
    description varchar(200) NOT NULL,
    release_date date NOT NULL,
    duration	integer NOT NULL,
    mpa_id		integer NOT NULL,
    rate        integer,
    FOREIGN KEY (mpa_id)
       REFERENCES mpa (id)
);

CREATE TABLE IF NOT EXISTS likes
(
    film_id		integer NOT NULL,
    user_id 	integer NOT NULL,
    PRIMARY KEY (film_id, user_id),
    FOREIGN KEY (film_id)
       REFERENCES films(id),
    FOREIGN KEY (user_id)
       REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS friendship
(
    user_id		integer NOT NULL,
    friend_id 	integer NOT NULL,
    PRIMARY KEY (user_id, friend_id),
    FOREIGN KEY (user_id)
       REFERENCES users (id),
    FOREIGN KEY (friend_id)
       REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS film_genre
(
    film_id		integer NOT NULL,
    genre_id 	integer NOT NULL,
    PRIMARY KEY (film_id, genre_id),
 	FOREIGN KEY (film_id)
       REFERENCES films (id),
    FOREIGN KEY (genre_id)
       REFERENCES genres (id)
);



